{
  "uid" : "4b4757e66a1912dae1a509f688f20b0f",
  "name" : "categories",
  "children" : [ {
    "name" : "Test defects",
    "children" : [ {
      "name" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000118BAB7C160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "children" : [ {
        "name" : "Пользователь может осуществить поиск (failed)",
        "uid" : "74c0ca0b2e994a31",
        "parentUid" : "0763915740da414ba459e8076be7fd06",
        "status" : "broken",
        "time" : {
          "start" : 1608646680866,
          "stop" : 1608646680866,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "0763915740da414ba459e8076be7fd06"
    }, {
      "name" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000017A082CC100>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))",
      "children" : [ {
        "name" : "Пользователь может осуществить поиск",
        "uid" : "e224e0e3ee35ade6",
        "parentUid" : "5a9d1dfe35518a4cb6bfbdf6fae70533",
        "status" : "broken",
        "time" : {
          "start" : 1608646680866,
          "stop" : 1608646680866,
          "duration" : 0
        },
        "flaky" : false,
        "newFailed" : false,
        "parameters" : [ ]
      } ],
      "uid" : "5a9d1dfe35518a4cb6bfbdf6fae70533"
    } ],
    "uid" : "bdbf199525818fae7a8651db9eafe741"
  } ]
}